### ISSUE TITLE
Terminate resources - sam delete failed

### ISSUE THREAD

**Issue by AnuragMohapatra** [aws-samples/serverless-tasks-webapp#14]
While running the step to terminate resources with `sam delete` it would fail to delete the S3 bucket if there are versions on the bucket.

This is due to the fact that when the S3 bucket is created it is versioned-enabled, on performing delete on s3 bucket with the previous command provided - `aws s3 rm s3://uploads-tasks-app-<region>-<accountid> --recursive`

Now the cloud formation stack will fail to completely delete the S3 bucket thus the user has to manually remove the `delete-marker` versions before run the `sam delete` again.

Possible solutions:

1. Let the user know in advance this might be the case and provide proper instructions on removing the versions before `sam delete` this will help them to understand the s3 console a bit  OR,
2. Remove versioning on the bucket  OR,
3. If there is a cli command to force versioning removal then mention that as an extra step in case a user is facing such issue.

**Comment by mrichman** [comment]
Resolved in latest workshop updates: https://catalog.us-east-1.prod.workshops.aws/workshops/841ce16b-9d86-48ac-a3f6-6a1b29f95d2b/en-US/step-6
