### ISSUE TITLE
amplify configure fails with "spawn xdg-open ENOENT"

### ISSUE THREAD

**Issue by noobtron** [aws-samples/serverless-tasks-webapp#23]
In Step 0: Prerequisites while using Cloud9 IDE.
`amplify configure`  hits a bug described here https://github.com/aws-amplify/amplify-cli/issues/12004

Resolution:
xdg-utils needs to be installed prior running `amplify configure`

e.g. `sudo yum install xdg-utils -y`

**Comment by mrichman** [comment]
I hit this before as well. It needs to be fixed in the Amplify installer.
