### ISSUE TITLE
yaml copy paste

### ISSUE THREAD

**Issue by exenza** [aws-samples/serverless-tasks-webapp#6]
In Windows 10 using Firefox, copy yaml in workshop, paste in cloud9, whitespaces and indentation is wrong and requires tedious corrections which lead anyway to the template to compile and build.

I suggest to invite users to download the template.yaml file, edit it locally and upload to cloud9

**Comment by mrichman** [comment]
Can you tell me on which step in the workshop this is happening?

**Comment by exenza** [comment]
Step 1
- [Define a DynamoDB table]
Add the DynamoDB table to the SAM templateHeader anchor link

- [Create a Lambda function]
Create a Lambda function

**Comment by mrichman** [comment]
Unable to reproduce. Closing.
